# TASK 1
dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [ ]:
import pandas as pd

dataset_url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"

df = pd.read_csv(dataset_url)

total_sales = df['Global_Sales'].sum()
highest_sales_game = df.loc[df['Global_Sales'].idxmax(), 'Name']

print("Total global sales:", total_sales)
print("Game with the highest global sales:", highest_sales_game)

average_sales_regions = df.groupby('Genre')['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales'].mean()
top_genres = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
most_popular_genre_na = df.loc[df['NA_Sales'].idxmax(), 'Genre']
last_10_rows = df.tail(10)
top_platforms = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
market_share_percentages = (df.groupby('Genre')['Global_Sales'].sum() / total_sales) * 100
correlation_coefficient = df[['NA_Sales', 'EU_Sales']].corr().iloc[0, 1]

print("Average sales for each region:")
print(average_sales_regions)
print("\nTop 5 most popular game genres:")


## Task 2 English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [2]:
# Create a dictionary where English words are keys and their Spanish translations are values.

english_spanish_dict = {
    "hello": "hola",
    "world": "mundo",
    "goodbye": "adios",
    "python": "python",
    "programming": "programación",
    "difficulty": "dificultad"
}   

user_input = input("Enter an English word: ")

while user_input!= "exit":
    if user_input in english_spanish_dict:
        print(english_spanish_dict[user_input])
    elif user_input.lower() == "exit":
        break
    else:
        print("Translation not available.")
    
    user_input = input("Enter an English word: ")

        


Translation not available.
hola



## Task 3 Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [ ]:
def classify_emails(emails):
    important_emails = []
    promotion_emails = []
    spam_emails = []

    important_emails_keywords = ["important","urgent","attention"]
    promotion_emails_keywords = ["advertise", "promotion","deal"]

    for email in emails:
        if important_emails_keywords[0] in email.lower() or important_emails_keywords[1] in email.lower() or important_emails_keywords[2] in email.lower():
            important_emails.append(email)
        elif promotion_emails_keywords[0] in email.lower() or promotion_emails_keywords[1] or promotion_emails_keywords[2]:
            promotion_emails.append(email)
        else:
            spam_emails.append(email)


    return important_emails, promotion_emails, spam_emails


emails = ["Hello, I need a new shirt. Please send it to my address.", "Dear friend, I would like to buy a new pair of pants. Can you please send it to our office?", "I found a great deal on a shoe! Would you like to buy it?"]

important_emails, promotion_emails, spam_emails = classify_emails(emails)

print("Important Emails:")

for email in important_emails:
    print(email)


print("\nPromotion Emails:")

for email in promotion_emails:
    print(email)

print("\nSpam Emails:")

for email in spam_emails:
    print(email)




## Task 4 Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.

In [6]:


import numpy as np

products = ["Shirt", "Pants", "Shoes"]
shopping_cart = []
user_choice = ''

print("Welcome to the Online Store!")
print("\nAvailable products:")

for i, product in enumerate(products):
    print(f"{i+1}. {product}")

input("Select Product( 1 - 3 ) :\n")

while True:
    user_choice = input("Select Product( 1 - 3 ) :\n")
    if user_choice == 'q':
        break
    user_choice = int(user_choice)
    if user_choice >= 1 and user_choice <= 3:
        shopping_cart.append(products[user_choice - 1])
        print(f"Added {products[user_choice - 1]} to your shopping cart.")
        


print("\n\nShopping Cart:")
for item in shopping_cart:
    print(item)
    


Welcome to the Online Store!

Available products:
1. Shirt
2. Pants
3. Shoes
Added Pants to your shopping cart.
Added Shoes to your shopping cart.
Added Shoes to your shopping cart.
Added Pants to your shopping cart.
Pants
Shoes
Shoes
Pants


## Task 5
* Create two NumPy arrays of the same shape and perform element-wise addition on them.
* Calculate the element-wise product of two NumPy arrays.

In [9]:


import numpy as np

arrayA = np.random.rand(3, 3)
arrayB = np.random.rand(3, 3)

result_addition = arrayA + arrayB
result_product = arrayA * arrayB

print("Element-wise addition result:")

for row in result_addition:
    print(row)

print("\nElement-wise product result:")

for row in result_product:
    print(row)




Element-wise addition result:
[0.25790779 0.49694992 1.14482946]
[1.30647572 0.7621463  1.5476279 ]
[1.35548211 1.33190065 1.6989325 ]

Element-wise product result:
[0.01631296 0.03216306 0.20791205]
[0.4162355  0.136972   0.58546108]
[0.43204092 0.36094572 0.72150887]


## Task 6
* Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

* Concatenate two NumPy arrays horizontally and vertically.

In [14]:


import numpy as np

array = np.arange(12)

print("Original array:")
for row in array:
    print(row)

reshaped_array = array.reshape(3, 4)

print("\nReshaped array:")

for row in reshaped_array:
    print(row)




Original array:
0
1
2
3
4
5
6
7
8
9
10
11

Reshaped array:
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


## Task 7
* Reverse A List In Python Using Slicing


In [ ]:

Data_list = [1, 2, 3, 4, 5]

print("Original list:", Data_list)

print("Reversed list:", Data_list[::-1])



# TASK 8
You need to download the GitHub Desktop software, push your lab task to your GitHub account, and share the link on GCR as a submission.